# Generated by Django 5.0.4 on 2024-04-27 08:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_date',
            new_name='datetime_from',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='duration',
        ),
        migrations.AddField(
            model_name='appointment',
            name='datetime_to',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
