# Generated by Django 5.0.4 on 2024-04-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_remove_doctorschedule_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='static/doctors/'),
        ),
        migrations.DeleteModel(
            name='DoctorSchedule',
        ),
    ]
